env:
  TERM: xterm-256color

# Auto-start every alacritty with tmux
# shell:
#   program: /bin/zsh
#   args:
#     - -l
#     - -c
#    - "tmux attach || tmux"  # attaches the last used session
#     - "tmux attach -d -t alacritty || tmux new -s alacritty" # attaches session named 'alacritty'

window:
  dimensions:
    columns: 105
    lines: 30
  decorations: buttonless
    # decorations: full, none, transparent, buttonless
  
  startup_mode: Windowed

  padding:
    x: 10
    y: 5

scrolling:
 history: 10000

# tabspaces: 4

draw_bold_text_with_bright_colors: true

font:
  normal:
    # family: 'SF Mono Powerline'
    # family: 'Ubuntu Mono derivative Powerline'
    # family: 'Fira Code Retina'
    family: 'Iosevka Term'
    # family: 'Iosevka Nerd Font Mono'
    style: Regular
  
  bold:
    # family: 'SF Mono Powerline'
    # family: 'Ubuntu Mono derivative Powerline'
    # family: 'Fira Code Retina'
    family : 'Iosevka Term'
    # family: 'Iosevka Nerd Font Mono'
    style: Bold
    
  italic:
    family: 'Iosevka Term'
    # family: 'Iosevka Nerd Font Mono'
    style: Italic
    
  size: 16.0
  
  # Thin strokes = true on retina displays, Non-retina disp = false
  use_thin_strokes: false

window.opacity: 1.0

cursor:
   # - ▇ Block
   # - _ Underline
   # - | Beam
  style: Underline
  thickness: 0.15
  unfocused_hollow: true

mouse:
  double_click: { threshold: 300 }   
  triple_click: { threshold: 300 }
  hide_when_typing: false
  
selection:
  save_to_clipboard: false

window.dynamic_title: false

live_config_reload: true

bell:
  animation: EaseOutQuint
  duration: 10
  color: '0xF44C8D'

debug:
  render_timer: false
  persistent_logging: false
  log_level: Warn
  print_events: false
  ref_test: false

alt_send_esc: false

key_bindings:
#   - { key: T,        mods: Command, command: { program: "open", args: ["-n", "/Applications/Alacritty.app"] } }
#   - { key: N,        mods: Command, command: { program: "/usr/local/bin/tmux", args: ["new-session","-d","-s","test"] } }
#   - { key: N,        mods: Command, command: { program: "/usr/local/bin/tmux", args: ["new-session","-d"] } }
#   - { key: N,        mods: Command, action: SpawnNewInstance }
  - { key: N,        mods: Command|Shift, command: { program: "/usr/local/bin/tmux", args: ["new-session","-d"] } }
  - { key: T,        mods: Command, command: { program: "/usr/local/bin/tmux", args: ["new-window"] } }
  - { key: V,        mods: Command, action: Paste                        }
  - { key: C,        mods: Command, action: Copy                         }
# - { key: Q,        mods: Command, action: Quit                         }
  - { key: W,        mods: Command, action: Quit                         }
  - { key: Q,        mods: Alt|Shift, command: { program: "/usr/local/bin/tmux", args: ["kill-window"] } }
  - { key: Q,        mods: Command, command: { program: "/usr/local/bin/tmux", args: ["kill-pane"] } }
  - { key: S,        mods: Command, command: { program: "/usr/local/bin/tmux", args: ["split-window", "-h"] } }
  - { key: B,        mods: Command, command: { program: "/usr/local/bin/tmux", args: ["split-window", "-b"] } }
  - { key: Key1,     mods: Command, command: { program: "/usr/local/bin/tmux", args: ["selected window", "-t", "1"] } }
  - { key: Key2,     mods: Command, command: { program: "/usr/local/bin/tmux", args: ["selected window", "-t", "2"] } }
  - { key: Key3,     mods: Command, command: { program: "/usr/local/bin/tmux", args: ["selected window", "-t", "3"] } }
  - { key: Key4,     mods: Command, command: { program: "/usr/local/bin/tmux", args: ["selected window", "-t", "4"] } }
  - { key: Key5,     mods: Command, command: { program: "/usr/local/bin/tmux", args: ["selected window", "-t", "5"] } }
  - { key: Key6,     mods: Command, command: { program: "/usr/local/bin/tmux", args: ["selected window", "-t", "6"] } }
  - { key: Key7,     mods: Command, command: { program: "/usr/local/bin/tmux", args: ["selected window", "-t", "7"] } }
  - { key: Key8,     mods: Command, command: { program: "/usr/local/bin/tmux", args: ["selected window", "-t", "8"] } }
  - { key: Key9,     mods: Command, command: { program: "/usr/local/bin/tmux", args: ["selected window", "-t", "9"] } }
  - { key: Delete,                  chars: "\x1b[3~"                     }
  - { key: Key1,     mods: Alt,           chars: "©"                  }
  - { key: Key2,     mods: Alt,           chars: "@"                  }
  - { key: Key3,     mods: Alt,           chars: "£"                  }
  - { key: Key4,     mods: Alt,           chars: "$"                  }
  - { key: Key5,     mods: Alt,           chars: "∞"                  }
  - { key: Key6,     mods: Alt,           chars: "§"                  }
  - { key: Key7,     mods: Alt,           chars: "|"                  }
  - { key: Key8,     mods: Alt,           chars: "["                  }
  - { key: Key9,     mods: Alt,           chars: "]"                  }
  - { key: Key0,     mods: Alt,           chars: "≈"                  }
  - { key: Grave,    mods: Alt,           chars: "~"                  }  
  - { key: Equals,   mods: Command, action: IncreaseFontSize             }
  - { key: Key0,     mods: Command, action: ResetFontSize                }
  - { key: Equals,   mods: Command, action: IncreaseFontSize             }
  - { key: Minus,    mods: Command, action: DecreaseFontSize             }
  - { key: Left,     mods: Alt,     chars: "\x1bb"                       }
  - { key: Right,    mods: Alt,     chars: "\x1bf"                       }
  - { key: Left,     mods: Command, chars: "\x1bOH",   mode: AppCursor   } # Home
  - { key: Right,    mods: Command, chars: "\x1bOF",   mode: AppCursor   } # End  

