env:
  TERM: xterm-256color

# Auto-start every alacritty with tmux
# shell:
#   program: /bin/zsh
#   args:
#     - -l
#     - -c
#    - "tmux attach || tmux"  # attaches the last used session
#     - "tmux attach -d -t alacritty || tmux new -s alacritty" # attaches session named 'alacritty'

window:
  dimensions:
    columns: 100
    lines: 26
  decorations: buttonless
    # decorations: full, none, transparent, buttonless
  
  startup_mode: Windowed

  padding:
    x: 10
    y: 5

scrolling:
 history: 1000

# tabspaces: 4

draw_bold_text_with_bright_colors: true

font:
  normal:
    family: 'Iosevka Term'
    style: Regular
  
  bold:
    family : 'Iosevka Term'
    style: Bold
    
  italic:
    family: 'Iosevka Term'
    style: Italic
    
  size: 16.0
  
  Thinstrokes: true # on retina displays: true / Non-retina: false
  AppleFontSmoothing: true

window.opacity: 1.0

cursor:
   # - ▇ Block
   # - _ Underline
   # - | Beam
  style: Underline
  thickness: 0.15
  unfocused_hollow: true

mouse:
  double_click: { threshold: 300 }   
  triple_click: { threshold: 300 }
  hide_when_typing: false
  
selection:
  save_to_clipboard: false

window.dynamic_title: false

live_config_reload: true

bell:
  animation: EaseOutQuint
  duration: 10
  color: '0xF44C8D'

debug:
  render_timer: false
  persistent_logging: false
  log_level: Warn
  print_events: false
  ref_test: false

window.option_as_alt: false

key_bindings:
  - { key: T,        mods: Command, command: { program: "/opt/homebrew/bin/Alacritty" } }
  - { key: V,        mods: Command, action: Paste                        }
  - { key: C,        mods: Command, action: Copy                         }
  - { key: W,        mods: Command, action: Quit                         }
  - { key: Delete,                  chars: "\x1b[3~"                     }
  - { key: Key1,     mods: Alt,           chars: "©"                  }
  - { key: Key2,     mods: Alt,           chars: "@"                  }
  - { key: Key3,     mods: Alt,           chars: "£"                  }
  - { key: Key4,     mods: Alt,           chars: "$"                  }
  - { key: Key5,     mods: Alt,           chars: "∞"                  }
  - { key: Key6,     mods: Alt,           chars: "§"                  }
  - { key: Key7,     mods: Alt,           chars: "|"                  }
  - { key: Key8,     mods: Alt,           chars: "["                  }
  - { key: Key9,     mods: Alt,           chars: "]"                  }
  - { key: Key0,     mods: Alt,           chars: "≈"                  }
  - { key: Grave,    mods: Alt,           chars: "~"                  }  
  - { key: Equals,   mods: Command, action: IncreaseFontSize             }
  - { key: Key0,     mods: Command, action: ResetFontSize                }
  - { key: Equals,   mods: Command, action: IncreaseFontSize             }
  - { key: Minus,    mods: Command, action: DecreaseFontSize             }
  - { key: Left,     mods: Alt,     chars: "\x1bb"                       }
  - { key: Right,    mods: Alt,     chars: "\x1bf"                       }
  - { key: Left,     mods: Command, chars: "\x1bOH",   mode: AppCursor   } # Home
  - { key: Right,    mods: Command, chars: "\x1bOF",   mode: AppCursor   } # End  

