[colors]
[colors.primary]
background = "#2a1f1d"
foreground = "#e0dbb7"
[colors.normal]
black = "#573d26"
red = "#be2d26"
green = "#6ba18a"
yellow = "#e99d2a"
blue = "#5a86ad"
magenta = "#ac80a6"
cyan = "#74a6ad"
white = "#e0dbb7"
[colors.bright]
black = "#9b6c4a"
red = "#e84627"
green = "#95d8ba"
yellow = "#d0d150"
blue = "#b8d3ed"
magenta = "#d19ecb"
cyan = "#93cfd7"
white = "#fff9d5"
