# From: https://github.com/kepano/flexoki/blob/main/alacritty/flexoki-dark.yaml
[colors]
[colors.primary]
background = "0x282726"
foreground = "0xFFFCF0"
[colors.cursor]
text = "0xFFFCF0"
cursor = "0xFFFCF0"
[colors.normal]
black = "0x100F0F"
red = "0xAF3029"
green = "0x66800B"
yellow = "0xAD8301"
blue = "0x205EA6"
magenta = "0xA02F6F"
cyan = "0x24837B"
white = "0xFFFCF0"
[colors.bright]
black = "0x100F0F"
red = "0xD14D41"
green = "0x879A39"
yellow = "0xD0A215"
blue = "0x4385BE"
magenta = "0xCE5D97"
cyan = "0x3AA99F"
white = "0xFFFCF0"
[colors.dim]
black = "0x100F0F"
red = "0xAF3029"
green = "0x66800B"
yellow = "0xAD8301"
blue = "0x205EA6"
magenta = "0xA02F6F"
cyan = "0x24837B"
white = "0xFFFCF0"
