# From: https://github.com/projekt0n/github-theme-contrib/raw/main/themes/alacritty/github_light.yml
[colors]
[colors.primary]
background = "0xffffff"
foreground = "0x1F2328"
[colors.cursor]
text = "0xffffff"
cursor = "0x1f2328"
[colors.normal]
black = "0x24292f"
red = "0xcf222e"
green = "0x116329"
yellow = "0x4d2d00"
blue = "0x0969da"
magenta = "0x8250df"
cyan = "0x1b7c83"
white = "0x6e7781"
[colors.bright]
black = "0x57606a"
red = "0xa40e26"
green = "0x1a7f37"
yellow = "0x633c01"
blue = "0x218bff"
magenta = "0x8250df"
cyan = "0x1b7c83"
white = "0x6e7781"
