[colors]
[colors.primary]
background = "#1a1a1a"
foreground = "#fafafa"
[colors.normal]
black = "#1a1a1a"
red = "#f4005f"
green = "#98e024"
yellow = "#fa8419"
blue = "#9d65ff"
magenta = "#f4005f"
cyan = "#58d1eb"
white = "#fafafa"
[colors.bright]
black = "#625e4c"
red = "#f4005f"
green = "#98e024"
yellow = "#e0d561"
blue = "#9d65ff"
magenta = "#f4005f"
cyan = "#58d1eb"
white = "#ffffff"
