[colors]
[colors.primary]
foreground = "#64526F"
background = "#FAF7EE"
[colors.cursor]
cursor = "#64526F"
text = "#FAF7EE"
[colors.normal]
black = "#FAF7EE"
red = "#DF201C"
green = "#009F6B"
yellow = "#DB742E"
blue = "#3980C2"
magenta = "#29A0AD"
cyan = "#6B3062"
white = "#64526F"
[colors.bright]
black = "#9F93A1"
red = "#DF201C"
green = "#009F6B"
yellow = "#DB742E"
blue = "#3980C2"
magenta = "#29A0AD"
cyan = "#6B3062"
white = "#64526F"
